cp -f ~/.alias ~/dotfiles/.alias
cp -f ~/.bashrc ~/dotfiles/.bashrc
cp -f ~/.config/fish/config.fish ~/dotfiles/.config/fish/config.fish
cp -f ~/.config/fish/functions/fish_user_key_bindings.fish ~/dotfiles/.config/fish/functions/fish_user_key_bindings.fish
cp -f ~/.config/fish/functions/fzf_key_bindings.fish ~/dotfiles/.config/fish/functions/fzf_key_bindings.fish
cp -f ~/.config/i3/config ~/dotfiles/.config/i3/config
cp -f ~/.config/kitty/kitty.conf ~/dotfiles/.config/kitty/kitty.conf
cp -f ~/.config/qutebrowser/config.py ~/dotfiles/.config/qutebrowser/config.py
cp -f ~/.config/starship.toml ~/dotfiles/.config/starship.toml
cp -f ~/.config/vifm/vifmrc ~/dotfiles/.config/vifm/vifmrc
cp -f ~/.fzf.bash ~/dotfiles/.fzf.bash
cp -f ~/.vimrc ~/dotfiles/.vimrc
cp -f ~/.xkt.vim ~/dotfiles/.xkt.vim
